name: JSON check

on:
  push:
    paths:
      - "**.json"
  pull_request:

jobs:
  json_validator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: json-syntax-check
        uses: limitusus/json-syntax-check@v1
        with:
          pattern: "\\.json$"
